### ISSUE TITLE
Works on a Raspberry Pi 4?

### ISSUE THREAD

**Issue by KrakenReef** [pideck/pideck-distro#5]
Hi!

I'm trying to init the 0.2 distro of PiDeck on a Raspberry pi 4 but, i can't.

Don't boot, only black screen.

Does the Pideck runs on a pi4? 

Thanks in advance.

**Comment by danielhjames** [comment]
That's a good question, the 0.2 image has not been tested on the Pi 4 by us. More likely is that your download or flashing process was corrupted. Is the checksum for your download ok?

**Comment by KrakenReef** [comment]
Thanks for your help Danielhjames, and sorry for the delay in my answer.

I can't find the .bmap file for disto 0.2. The checksum hash for my 02.img is 87ca44a05272eb113538e450b66eec3438ec1df3c36d48f648dd682f7cbd797b

Today, i have downloaded the 0.1 distro, and flased to the sd. The checksum in this release is the same that the .bmap file inlcude on assets for this release: 41884dc651d5a60a48d49157fc8f24d2ff1513a884cd3a50d3454c4d016bb416

But unfortunately i have the same scenario than distro 0.2, blackscreen on my pi4.

Regards.

**Comment by danielhjames** [comment]
Thanks for checking, it seems the Pi 4 needs a different fimware and kernel package. Some people have made this work by copying these packages from compatible distros into an image built for the Pi 3.

**Comment by KrakenReef** [comment]
Thanks danielhjames.

I have done these modifications on my Pi4 and now PiDeck can run on it.

**Comment by danielhjames** [comment]
Thanks for letting us know @KrakenReef ! Which versions of packages did you copy into the image to get it working please?

**Comment by emaines** [comment]
@KrakenReef I'd also like to know the details of what fimware and kernel package modifications were done to make PiDeck work with the Pi4? Cheers

**Comment by KrakenReef** [comment]
Hi.
I only used the pi4 to my first attemp with pideck. After that, i mounted the pideck on a pi3 b+ with the official touchscreen and a case for all.
To make work the Pideck on my Pi4, I added to the boot folder the files: start4.elf, kernel7l.img, fixup4.dat and bcm2711-rpi-4-b.dtb.
These files were from a Raspbian distribution with kernel 4.19.75. The pi4 firmware for that moment was 514670a2 version, but after I updated the pi4 fw when i try to load a pideck distribution on my pi4, the keyboard and mouse does not work at  all. Raspberry detects the devices (you can see the logs on var/logs/) but no keyboard or mouse so it's impossible to use the pideck with de pi4 connected a monitor.
